### ISSUE TITLE
Error in running_processes()

### ISSUE THREAD

**Issue by AndiH** [wookayin/gpustat#1]
I get the following error when calling `gpustat` while an actual GPU process is running. If no process involving GPUs is running, the output is correct as expected.

Error:

```
$ ./gpustat
Traceback (most recent call last):
  File "./gpustat", line 260, in <module>
    main(args)
  File "./gpustat", line 224, in main
    gpu_stats.update_process_information()
  File "./gpustat", line 184, in update_process_information
    processes = self.running_processes()
  File "./gpustat", line 179, in running_processes
    process_entry.update(pid_map[pid])
TypeError: 'NoneType' object is not iterable
```

The `nvidia-smi` output at the time ist correct:

```
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     11812    C   ./juspic.x                                      96MiB |
```

Any ideas why the list seems to be empty? (I have not yet debugged it myself.)

**Comment by wookayin** [comment]
It looks that in some situations the list of processes from `nvidia-smi --query-gpu-apps` and that from `ps` are different. Hope it is now fixed.
