### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by wookayin** [wookayin/gpustat#10]

**Comment by wookayin** [comment]
Partly included in v0.3.0

**Comment by Stonesjtu** [comment]
When the json output is stable, maybe we can detach the data collecting module and display module. Then we can request GPU usages from different remote data collecting nodes via HTTP or something else.

**Comment by wookayin** [comment]
Exactly, I am hoping to decouple them so that we can collect and display GPU usages from different machines. Working on these, so stay tuned :-)

**Comment by rubenvereecken** [comment]
Any news on this? Wouldn't mind giving a helping hand.

**Comment by Stonesjtu** [comment]
I'd like to recommend an NVML binding for Python to collect GPU information rather than `nvidia-smi`. This library would significantly simplify the code base for information gathering.

https://github.com/jonsafari/nvidia-ml-py

**Comment by wookayin** [comment]
@Stonesjtu Quite agree with you. It provides more information, and we could turn `gpustat` into a human-friendly wrapper with cleaner abstraction, providing monitoring functionalities as well. For JSON output formats, I plan to make it fully compatible with a XML format from `nvidia-smi -q -x`.

**Comment by Stonesjtu** [comment]
I'm trying to move the `nvidia-smi` API to `nvidia-ml-py`

**Comment by gyscos** [comment]
JSON output is a great feature!

A few notes on the current implementation:
* Fields with a dot (like `utilization.gpu`) make them harder to use in many JSON clients (like `jq`).
* Numeric fields could use numeric values instead of strings

**Comment by Stonesjtu** [comment]
@gyscos I think fileds with dot can be naturally organized into sub-dict. e.g. 
```json
{
'utilization': 
  {
  'gpu': 40,
  'memory': 30,
  }
}
```

**Comment by wookayin** [comment]
I plan to make a few of breaking changes towards 1.0, such as units and numerical values.

**Comment by cceyda** [comment]
would it be possible to get driver_version and cuda_version (if available) in the json output?

**Comment by wookayin** [comment]
@cceyda driver version has been added in the JSON output.

However, cuda version isn't something gpustat cannot retrieve from querying nvidia driver. The cuda runtime may vary by applications and dynamic libraries being loaded. Please refer to https://stackoverflow.com/questions/9727688/how-to-get-the-cuda-version for how to get the cuda version.

**Comment by wookayin** [comment]
There won't be breaking changes in the units (e.g. MB vs bytes) but later we will add a flag/option to specify the units.
