### ISSUE TITLE
Hide processes at all by default?

### ISSUE THREAD

**Issue by nizhib** [wookayin/gpustat#101]
It's quite unexpected to have different flags for showing commands, pids etc. including users yet users are shown by default regardless the presence of the flag and there is no option to hide them.

Maybe we can just hide the last column by default or at least add the `--no-users/processes` option?

Use case: I have sequential `ssh host gpustat` calls as a bash alias and depending on the number of processes on different machines I get a mess instead of just a simple table with an overall gpu load across the inventory.

**Comment by wookayin** [comment]
Adding an option to suppress process information makes sense, although it wouldn't be a default behavior.

**Comment by wookayin** [comment]
Fixed in #133.
