### ISSUE TITLE
MIG support - GPU utilization, etc.

### ISSUE THREAD

**Issue by yskimno1** [wookayin/gpustat#106]
![image](https://user-images.githubusercontent.com/38938677/126946795-1910e863-01f1-4841-ab1a-2c78ba32da96.png)

![image](https://user-images.githubusercontent.com/38938677/126946872-7c1ceee1-bb27-4c3f-a87f-5f2b99c37371.png)

When I use gpustat in MIG mode A100, I cannot see divided devices.
I think gpustat command should also support GPUs in MIG-mode. (Each divided devices' memory stats & compute utilizations)

Thanks.

**Comment by wookayin** [comment]
Thanks for your suggestion. Let's discuss in #102.
