### ISSUE TITLE
Misssing flags

### ISSUE THREAD

**Issue by kobiche** [wookayin/gpustat#109]
I tried setting the flags: 
- --show-all 
- --show-full-cmd
- --show-codec

and they are unrecognized by the program. Am I missing something? Because they appear in the README file

**Comment by wookayin** [comment]
New flags are not released as stable, sorry. Try installing `gpustat==1.0.0b1` or the nightly: `pip install git+https://github.com/wookayin/gpustat`

**Comment by kobiche** [comment]
Oh, sad to hear that. But I'll wait :)
