### ISSUE TITLE
No package metadata was found for gpustat

### ISSUE THREAD

**Issue by ant0n-anon** [wookayin/gpustat#112]
OS: Arch Linux x86_64
Kernel: 5.15.7-arch1-1
Plasma: Plasma 5.23.4

After latest arch update:

```
Traceback (most recent call last):
  File "/usr/bin/gpustat", line 33, in <module>
    sys.exit(load_entry_point('gpustat==0.6.0', 'console_scripts', 'gpustat')())
  File "/usr/bin/gpustat", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for gpustat
```

**Comment by Stonesjtu** [comment]
try python -m gpustat.  Seems you have invoked gpustat with the wrong python interpreter.

**Comment by ant0n-anon** [comment]
@Stonesjtu : no module named gpustat. 

i used to always use gpustat -cp --watch

**Comment by ant0n-anon** [comment]
seems to be a python problem with the new update. many other people having issues with many other software after this last update.

**Comment by herrenP** [comment]
Has anyone found a solution/work around?

**Comment by herrenP** [comment]
I should mention that I prior to the solution installed `pynvml` but I am not sure if that was ultimately needed or not.

**Comment by wookayin** [comment]
Have you tried installing it from a clean status, like `pip install --force-reinstall gpustat` ? Your python packages probably have got corrupted.

**Comment by ant0n-anon** [comment]
> Have you tried installing it from a clean status, like `pip install --force-reinstall gpustat` ? Your python packages probably have got corrupted.

that was it! thank you!!!
