### ISSUE TITLE
[BUG] memory size is different

### ISSUE THREAD

**Issue by sorrowyn** [wookayin/gpustat#116]
memory size is different
![图片](https://user-images.githubusercontent.com/19569162/157165758-4f6add13-16d9-4bfe-96c6-3a946c781ef4.png)

**Comment by XuehaiPan** [comment]
`nvidia-smi` and [`nvidia-ml-py`](https://pypi.org/project/nvidia-ml-py/#history) give different results with the NVIDIA R510 driver.

```
$ pip3 install -U nvidia-ml-py==11.515.0
```

![R510](https://user-images.githubusercontent.com/16078332/157428852-70fe235c-9461-4447-a1d7-f70bd446a113.png)

**Comment by sorrowyn** [comment]
Thank you for your sincere reply

**Comment by wookayin** [comment]
See https://github.com/wookayin/gpustat/pull/107#issuecomment-893513321, and I will mark this as a duplicate in favor of #107. I will need to update gpustat to use the official bindings `nvidia-ml-py`==11.515.0` so that process information can be correctly retrieved.
