### ISSUE TITLE
Not supported?

### ISSUE THREAD

**Issue by git2013vb** [wookayin/gpustat#122]
I tried it using 

`gpustat -cpFP --watch`

I use Debian 11.

Here my result : 

![image](https://user-images.githubusercontent.com/13235119/167581911-d4ea9ff3-9641-43cb-9029-e00768929d0e.png)

When I run something in gpu it sow me the amount of memory used only:

![image](https://user-images.githubusercontent.com/13235119/167582249-2ef2d942-5ff1-42db-95d8-666ffb112d89.png)

Any hints? I miss something?

Thanks.

**Comment by Stonesjtu** [comment]
The GPU is too old to report the process running on it.

**Comment by wookayin** [comment]
Can you show me the output of `gpustat --debug`? I guess the graphics driver is too old, lacking the process-related APIs.

**Comment by git2013vb** [comment]
> Can you show me the output of `gpustat --debug`? I guess the graphics driver is too old, lacking the process-related APIs.

Sure :)

```
(base) vale@debianace:~$ gpustat --debug
debianace            Tue May 24 09:21:01 2022  390.144
[0] GeForce GT 650M  | 47'C,  ?? % |     0 /  1999 MB | (Not Supported)
(base) vale@debianace:~$ 

```

**Comment by git2013vb** [comment]
No problem.  But I prefer do not use pip for installing it. (I have anaconda installed)
So in alternative I downloaded the source code and I run `python ./setup.py bdist`. Then I extract the .gz then I run it from the folder where the compiled file was 
```
(base) vale@debianace:~/Downloads/apps/nvidia/gpustat-master/dist/home/vale/anaconda3/bin$ ./gpustat  --debug
debianace            Tue May 24 12:57:21 2022  390.144
[0] GeForce GT 650M  | 49'C,  ?? % |     0 /  1999 MB | (Not Supported)
(base) vale@debianace:~/Downloads/apps/nvidia/gpustat-master/dist/home/vale/anaconda3/bin$ 
```

I got it right anyway?

**Comment by wookayin** [comment]
> But I prefer do not use pip for installing it. (I have anaconda installed)

Using `pip` inside anaconda is *perfectly fine* and has absolutely no problems. Make sure `pip` refers to the one in your anaconda bin path.

I'm pretty sure you didn't do the installation correctly. `setup.py bdist` does not install the package. You'll need to do `pip install -e` or `python setup.py develop`.

Or If you have cloned or downloaded the project, you can simply run `python -m gpustat --debug`.

Please verify your steps are correct by checking `gpustat -v` (should say 1.0.0.dev2)

**Comment by xk-huang** [comment]
> Oh sorry, I forgot the debug feature were added in the dev (unreleased) version. It would be appreciated if you can install the dev version (`pip install --force-reinstall git+https://github.com/wookayin/gpustat`) and try again.

Solve the #95 :smile:

**Comment by wookayin** [comment]
Let me close this issue due to lack of activity. I believe this is because your graphics driver is too old, so please try upgrading the nvidia driver if possible. If you still have the problem, please inform us the following and I will reopen the issue:

- Your installed nvidia-driver version (390.144)
- The name/model of your nvidia graphics card (e.g. GT 650M)
- gpustat version  (Please try the latest HEAD version and `--debug` option as requested above)
- The version of `pynvml` installed: e.g.,`pip freeze | grep nvidia`
- The full output of `nvidia-smi`

**Comment by git2013vb** [comment]
> Let me close this issue due to lack of activity. I believe this is because your graphics driver is too old, so please try upgrading the nvidia driver if possible. If you still have the problem, please inform us the following and I will reopen the issue:
> 
>     * Your installed nvidia-driver version (390.144)
> 
>     * The name/model of your nvidia graphics card (e.g. GT 650M)
> 
>     * gpustat version  (Please try the latest HEAD version and `--debug` option as requested above)
> 
>     * The version of `pynvml` installed: e.g.,`pip freeze | grep nvidia`
> 
>     * The full output of `nvidia-smi`

Sorry for the delay :) I post all info I can for completion:

```base) vale@debianace:~$ gpustat -v
gpustat 0.6.0
(base) vale@debianace:~$ nvidia-smi
Sat Sep  3 04:00:21 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.151                Driver Version: 390.151                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 650M     Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   40C    P8    N/A /  N/A |   1166MiB /  1999MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
(base) vale@debianace:~$ 

(base) vale@debianace:~$ pip freeze | grep nvidia
nvidia-ml-py3 @ file:///tmp/build/80754af9/nvidia-ml_1621428042568/work

```
My current driver is 390.151

I cannot update the latest NVIDIA driver because my card is not supported by them anymore, Nevertheless I can use it flawless (I tested I can run pvkrun, optirun and primusrun at same time with no problems)
 
I guess I don't have yet the latest gpustat version installed. it's mandatory or my info here are enough?  (Its not a urgent matter to me so you can answer when you have time ) 

Thanks

**Comment by wookayin** [comment]
gpustat 1.0.0+ supports driver version 450.00 or higher. gpustat 0.6.0 would work with R390.151, but there might be some bugs.

You can try `gpustat --debug` to get more information about errors with the v1.0.0 version, but my understanding is that the graphics card (GT 650M) is too old so it does not support listing running processes.
