### ISSUE TITLE
process basename includes command args

### ISSUE THREAD

**Issue by cdhinrichs** [wookayin/gpustat#124]
Problem: if I use the -c flag, I would like to know the command that was called, but not its arguments. For example, if chromium is one of the processes to be shown, I would like it to simply say `chromium`, and not 

```
chromium --type=gpu-process --enable-gpu-rasterization --enable-crashpad --crashpad-handler-pid=XXXX --enable-crash-reporter=,for Linux Mint --change-stack-guard-on-fork=enable --gpu-preferences=WAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAABAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA== --shared-files
```

I found that by adding the following line to core.py after line 303 fixed the issue for me. This splits everything off of the command after the first space, if there is one.
`process['command'] = process['command'].split(' ')[0]`

**Comment by XuehaiPan** [comment]
Just upgrade your `psutil` to `>= 5.6.6` will fix this.

```bash
pip3 install -U 'psutil >= 5.6.6'
```

See https://github.com/giampaolo/psutil/commit/edb20f664f28653dcdd24f0bf0191984738dca6e

**Comment by cdhinrichs** [comment]
I see - apparently I was using /usr/bin/gpustat which used the system python, rather than my conda version which is more up to date.
