### ISSUE TITLE
Disable apt to install gpustat

### ISSUE THREAD

**Issue by GoingMyWay** [wookayin/gpustat#126]
Hi, I tried to use `apt` in Ubuntu to install gpustat and it changed the cuda driver, leading to the driver mismatch. It took me 2 hours to detect this issue. Can you disable `apt` to install gpustat?

**Comment by wookayin** [comment]
I do not maintain apt repository (the maintainer of the `gpustat` package in the aptitutde is not me) and never intended to have it. A third-party uploaded the package so I don't have a control over it.

I will try to reach out the maintainer to see if this would be possible. Actually there is absolutely no reason for apt-installed gpustat should install a nvidia driver.

**Comment by GoingMyWay** [comment]
> I do not maintain apt repository (the maintainer of the `gpustat` package in the aptitutde is not me) and never intended to have it. A third-party uploaded the package so I don't have a control over it.
> 
> I will try to reach out the maintainer to see if this would be possible. Actually there is absolutely no reason for apt-installed gpustat should install a nvidia driver.

I see. Thanks for the clarification.

**Comment by wookayin** [comment]
Contact Mo Zhou <cdluminate@gmail.com>.

**Comment by GoingMyWay** [comment]
> Contact Mo Zhou [cdluminate@gmail.com](mailto:cdluminate@gmail.com).

@wookayin Thanks for the help. I will contact Mo Zhou.
