### ISSUE TITLE
installing gpustat causes new Cuda drivers to overwrite

### ISSUE THREAD

**Issue by OmegAshEnr01n** [wookayin/gpustat#139]
Hi,

So I have a container for an Nvidia/cuda image. The container comes with an installation of Cuda and its drivers. 
After installation I get this error -> Failed to initialize NVML: Driver/library version mismatch

**Comment by wookayin** [comment]
What is the nvidia driver version are you using in the docker image (before installing gpustat)?

Installation of gpustat does not affect nor update CUDA libraries or NVIDIA drivers. How did you install gpustat?

**Comment by wookayin** [comment]
Try rebooting. I don't think this has something to do with gpustat.

More references:

https://forums.developer.nvidia.com/t/black-screen-with-nvidia-turned-on-instead-intel-and-failed-to-initialize-nvml-driver-library-version-mismatch/210594/2
https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch
