### ISSUE TITLE
Random Crashes with exit code 1 in version 1.0

### ISSUE THREAD

**Issue by ItsABlackScreen** [wookayin/gpustat#144]
**Describe the bug**

Upgraded from version 0.6.0 which has worked fine for a long time to 1.0 and the program crashes regularly with an exit code of 1 and no error messages. The time of the crashes is random, from a few minutes to almost an hour. 
Also initialized a new virtual env but the problem still occurs, and switching back to 0.6.0 stops the crashes. 

**Screenshots or Program Output**

```
$ gpustat --debug
> An error while retrieving `fan_speed`: Not Supported
Traceback (most recent call last):
  File "path/to/home/dir/.venv/lib64/python3.10/site-packages/gpustat/core.py", line 425, in get_gpu_info
    fan_speed = N.nvmlDeviceGetFanSpeed(handle)
  File "path/to/home/dir/.venv/lib64/python3.10/site-packages/pynvml.py", line 1942, in nvmlDeviceGetFanSpeed
    _nvmlCheckReturn(ret)
  File "path/to/home/dir/.venv/lib64/python3.10/site-packages/pynvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_NotSupported: Not Supported

> An error while retrieving `power_limit`: Not Supported
Traceback (most recent call last):
  File "path/to/home/dir/.venv/lib64/python3.10/site-packages/gpustat/core.py", line 461, in get_gpu_info
    power_limit = N.nvmlDeviceGetEnforcedPowerLimit(handle)
  File "path/to/home/dir/.venv/lib64/python3.10/site-packages/pynvml.py", line 2025, in nvmlDeviceGetEnforcedPowerLimit
    _nvmlCheckReturn(ret)
  File "path/to/home/dir/.venv/lib64/python3.10/site-packages/pynvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_NotSupported: Not Supported

> An error while retrieving `fan_speed`: Not Supported -> Total 1 occurrences.
> An error while retrieving `power_limit`: Not Supported -> Total 1 occurrences.
```
```
$ nvidia-smi
Fri Dec  2 13:31:01 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.56.06    Driver Version: 520.56.06    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   44C    P5    20W /  N/A |   1000MiB /  6144MiB |     21%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Environment information:**

 - OS: Fedora 36
 - NVIDIA Driver version: 520.56.06
 - The name(s) of GPU card: NVIDIA GeForce RTX 3060 Laptop GPU
 - gpustat version: 1.0.0
 - pynvml version: 
```
nvidia-ml-py                      11.495.46
nvidia-ml-py3                     7.352.0
```

Command used:
`
gpustat -cp --watch
`

**Comment by wookayin** [comment]
Strange. If python throws an error, then it should print some messages. I wonder if it was a segfault. I think the NotSupported error when retrieving fan speed and power limit is fine and not relevant here, it's just your RTX 3060 card not supporting these features.

If it often happens and reproducible not that difficultly (like up to an hour), then could you try `PYTHONFAULTHANDLER=1 gpustat -cp --watch --debug`? You can also try the latest development version (`pip install --upgrade 'gpustat @ git+https://github.com/wookayin/gpustat'`) where I add `sys.stderr.flush()` to ensure traceback is flushed before exiting.

**Comment by ItsABlackScreen** [comment]
I installed the latest version in a new venv and ran the command in two separate terminals at the same time. 
There are still no error messages except exit code 1 and still random crashes. 

Also the crashes don't occur at the same time, one process crashed in 2m 26s and the second concurrent process in 3m 25s. 
Was able to reproduce the non concurrent crashes on concurrent commands multiple times with various times gaps. 
Throughout this the v0.6 process continued without crashing.

**Comment by wookayin** [comment]
Hmm, so still no output at all? Do you have any screenshots/videos available? I'm not sure whether this is a python exception thrown outside or segfault (a crash from the nvml side). All the python errors should have been catched and printed, so I guess this is less likely the case.

One way to troubleshoot the bug, if you're willing to help, is to print some debug 
 messages before every single `N.nvmlDevice...` call, e.g.

```diff
+           print("N.nvmlDeviceGetName")
            name = _decode(N.nvmlDeviceGetName(handle))
+           print("N.nvmlDeviceGetUUID")
            uuid = _decode(N.nvmlDeviceGetUUID(handle))

            try:
+               print("N.nvmlDeviceGetTemperature")
                temperature = N.nvmlDeviceGetTemperature(
                    handle, N.NVML_TEMPERATURE_GPU
                )
            except N.NVMLError as e:
                log.add_exception("temperature", e)
                temperature = None  # Not supported
```

this will make the output *very* verbose and flooding, but would be OK when using the `--watch` mode.

**Comment by ItsABlackScreen** [comment]
So i went ahead and inserted the print statements, but still there were no error messages and just an exit code of 1.
I realized that the terminal was probably being cleared in the process by the --watch option, so i just dumped everything to a log file and *finally* have the error messages. 

This is from  after the last successful run till the process crashed 
```
Error on querying NVIDIA devices. Use --debug flag to see more details.
process no longer exists (pid=3949264)

Traceback (most recent call last):
  File "/path/to/home/dir/gpustat/.venv/lib64/python3.10/site-packages/psutil/_common.py", line 443, in wrapper
    ret = self._cache[fun]
AttributeError: 'Process' object has no attribute '_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/home/dir/gpustat/.venv/lib64/python3.10/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/path/to/home/dir/gpustat/.venv/lib64/python3.10/site-packages/psutil/_common.py", line 446, in wrapper
    return fun(self)
  File "/path/to/home/dir/gpustat/.venv/lib64/python3.10/site-packages/psutil/_pslinux.py", line 1687, in _parse_stat_file
    data = bcat("%s/%s/stat" % (self._procfs_path, self.pid))
  File "/path/to/home/dir/gpustat/.venv/lib64/python3.10/site-packages/psutil/_common.py", line 776, in bcat
    return cat(fname, fallback=fallback, _open=open_binary)
  File "/path/to/home/dir/gpustat/.venv/lib64/python3.10/site-packages/psutil/_common.py", line 764, in cat
    with _open(fname) as f:
  File "/path/to/home/dir/gpustat/.venv/lib64/python3.10/site-packages/psutil/_common.py", line 728, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/3949264/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/home/dir/gpustat/.venv/lib64/python3.10/site-packages/gpustat/cli.py", line 58, in print_gpustat
    gpu_stats = GPUStatCollection.new_query(debug=debug)
  File "/path/to/home/dir/gpustat/.venv/lib64/python3.10/site-packages/gpustat/core.py", line 600, in new_query
    gpu_info = get_gpu_info(handle)
  File "/path/to/home/dir/gpustat/.venv/lib64/python3.10/site-packages/gpustat/core.py", line 563, in get_gpu_info
    process["cpu_percent"] = cache_process.cpu_percent()
  File "/path/to/home/dir/gpustat/.venv/lib64/python3.10/site-packages/psutil/__init__.py", line 999, in cpu_percent
    pt2 = self._proc.cpu_times()
  File "/path/to/home/dir/gpustat/.venv/lib64/python3.10/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/path/to/home/dir/gpustat/.venv/lib64/python3.10/site-packages/psutil/_pslinux.py", line 1836, in cpu_times
    values = self._parse_stat_file()
  File "/path/to/home/dir/gpustat/.venv/lib64/python3.10/site-packages/psutil/_pslinux.py", line 1652, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=3949264)
GetCount
GetHandleByIndex
GetName
GetUUID
GetTemperature
GetFanSpeed
GetMemoryInfo
GetUtilizationRates
GetEncoderUtilization
GetDecoderUtilization
GetPowerUsage
GetEnforcedPowerLimit
GetComputeRunningProcess
GetGraphiceRunningProcesses
```
On three different runs the crash was exactly from the same reason. 
Also to note that the v0.6 process has been running fine the entire time (2 days and some change).

**Comment by wookayin** [comment]
@ItsABlackScreen Thank you very much for your work in figuring out the reason! 

```
FileNotFoundError: [Errno 2] No such file or directory: '/proc/3949264/stat'
process no longer exists (pid=3949264)
```

BTW What is the version of psutil installed? A relevant issue is #95 (first appeared in v1.0) but this is for `get_process_info`. We should apply the same fix to the problematic line:

```
                process['cpu_percent'] = ps_process.cpu_percent()
```

**Comment by ItsABlackScreen** [comment]
No problem, happy to help. 
Psutil version = 5.9.4

> 
> A relevant issue is #95 but this is for `get_process_info`. We should apply the same fix to the problematic line:
> 
>                 process['cpu_percent'] = ps_process.cpu_percent()

Hmm, maybe i am misunderstanding but isn't the problem in : 
```
process["cpu_percent"] = cache_process.cpu_percent()
```
My guess is that betwen the first call to cpu_percent and the second call the process is no longer there.
Wrapping that in try and catching `psutil.NoSuchProcess` seems to have worked and the exception is getting caught and the program no longer crashing.

**Comment by wookayin** [comment]
@ItsABlackScreen Can you try the latest version and see if the problem has been fixed?

**Comment by ItsABlackScreen** [comment]
@wookayin There have been no crashes since the fix, the issue is now resolved.
