### ISSUE TITLE
UserWarning: Failed to setupterm(kind='xterm'): setupterm: could not find terminfo database

### ISSUE THREAD

**Issue by pursuecong** [wookayin/gpustat#148]
my conda file move，the questions is now

**Comment by wookayin** [comment]
Please provide more detail in your quesiton.

Some pointers for you:
- https://askubuntu.com/questions/576318/how-to-add-xterm-to-terminfo
- https://stackoverflow.com/questions/12345675/screen-cannot-find-terminfo-entry-for-xterm-256color
