### ISSUE TITLE
Support anaconda's legacy pynvml package

### ISSUE THREAD

**Issue by DManowitz** [wookayin/gpustat#149]
At the moment, gpustat is the only package on conda-forge that relies on the official NVIDIA management library, rather than on the pynvml package.  That means it cannot be installed into an environment which is using any other package that depends on the pynvml package.

If gpustat were compatible with both packages and could be released in two versions, one with either package as a dependency, that would probably be ideal.

**Comment by wookayin** [comment]
In my opinion the legacy pynvml package should not be used and all other packages that depends on this non-official pynvml3 should be updated. But I understand there are many outdated, unmaintained softwares in the wild that we do not have much control.

As a workaround you can use gpustat < 1.0. I do not mantain conda packages for gpustat, so gpustat should be ideally installed with pip via PyPi.

**Comment by DManowitz** [comment]
Unfortunately, I'm on Windows, and gpustat < 1.0 uses blessings, rather than blessed, which doesn't work on Windows (https://github.com/erikrose/blessings/issues/21), so I can't use those versions.  Also, I didn't realize that you don't maintain the conda packages for gpustat.  I also now see that pynvml hasn't been updated since Dec. 2021, so I'll see if I can nudge the other packages to use the official bindings.

**Comment by DManowitz** [comment]
Also, do you have any plans to support the nvidia-ml-py 11.5xx versions?

**Comment by wookayin** [comment]
Yes, the master version already supports `nvidia-ml-py>11.495.46`, see #143.

But what happens if both the official bindings and unofficial legacy are installed as conda deps? I don't think there is no conflicting dependency between these two.

**Comment by DManowitz** [comment]
Both pynvml and nvidia-ml-py have constraints on their conda packages that prevent both of them from being installed at the same time (they each constrain the other package to version 999999999, which does not exist).

**Comment by wookayin** [comment]
@DManowitz do you still need this? what's the status of the anaconda's legacy pynvml package? (any links or information would be appreciated)

**Comment by wookayin** [comment]
The official pynvml bindings **nvidia-ml-py** should be used. If anaconda ships with a legacy package, that's their problem. Don't use the old software. gpustat can still be used with installing `nvidia-ml-py` via pip/PyPI.

If you disagree or have another corner case that needs to be resolved, please let me know.
