### ISSUE TITLE
module 'pynvml' has no attribute '_nvmlGetFunctionPointer'

### ISSUE THREAD

**Issue by BEpresent** [wookayin/gpustat#153]
**Describe the bug**

Calling `gpustat` leads to the following error:

**Screenshots or Program Output**

```
Traceback (most recent call last):
  File "/home/be/.local/bin/gpustat", line 5, in <module>
    from gpustat import main
  File "/home/be/.local/lib/python3.9/site-packages/gpustat/__init__.py", line 16, in <module>
    from .core import GPUStat, GPUStatCollection
  File "/home/be/.local/lib/python3.9/site-packages/gpustat/core.py", line 24, in <module>
    from gpustat.nvml import pynvml as N
  File "/home/be/.local/lib/python3.9/site-packages/gpustat/nvml.py", line 57, in <module>
    _original_nvmlGetFunctionPointer = pynvml._nvmlGetFunctionPointer
AttributeError: module 'pynvml' has no attribute '_nvmlGetFunctionPointer'
```

Please provide the output of `gpustat --debug` and `nvidia-smi`. Or attach screenshots if applicable.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/7645717/236204846-088fba56-df7d-4cec-8faa-0cd20a02229c.png">

**Environment information:**

 - OS: Debian 11.7
 - NVIDIA Driver version:  `NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4 `
 - The name(s) of GPU card: 2 T4
 - gpustat version: `gpustat --version` doesn't work, but I did pip install it so I assume it fetches the latest version `Successfully uninstalled gpustat-1.1`
 - pynvml version: `nvidia-ml-py                                 11.525.112`

**Additional context**

It should be noted that it has worked 2-3 weeks ago, but now it does not on 3 different machines I have tested.

**Comment by wookayin** [comment]
Thanks for the report. Hmm, I see `_nvmlGetFunctionPointer` still exists in 11.525.112 version:

https://github.com/wookayin/nvidia-ml-py/blob/11.525.112/pynvml.py#L853

Could you please try opening the file `/home/be/.local/lib/python3.9/site-packages/pynvml.py` and see if the function exists? It should be at around Line 852.

**Comment by herrenP** [comment]
I have the exact same issue. There is no `pynvml.py` in `$HOME/.local/lib/python3.10/site-packages/` for me. Only other packages. However, there is one in `/usr/lib/python3.10/site-packages` and the function is there:

```
~ > grep -n -m 1 _nvmlGetFunctionPointer /usr/lib/python3.10/site-packages/pynvml.py                                                                                                                                                                          5s
852:_nvmlGetFunctionPointer_cache = dict() # function pointers are cached to prevent unnecessary libLoadLock locking
```

I seem to recall having this issue before. Or at least very similar one. And I seem to recall a command to force reinstall all packages or something for Python.

**Comment by wookayin** [comment]
Thank you for the information. Yes, the pynvml should be the one that you get from your site-packages:
```
python -c 'import pynvml; print(pynvml.__file__)'
/usr/lib/python3.10/site-packages/pynvml.py
```

So apparently this `pynvml` seems to be coming from an old version of pynvml. This can happen, for instance, some other python packages install **legacy** nvidia-ml-py3 which might override pynvml; `pip list` can't tell this. So that's why I'm asking the checksum of the pynvml file to ensure the package hasn't been corrupted.

Although this is an user problem (or one of the downstream packages used in your project), I will try to add some fool-proof error messages when pynvml isn't alright.

**Comment by mattip** [comment]
xref https://github.com/ray-project/ray/issues/34196

**Comment by wookayin** [comment]
According to ray-project/ray#34196 (/cc @yuanwu2017), the problematic pynvml file comes from this third-party fork(?) that is 4 years ago.

- https://github.com/gpuopenanalytics/pynvml

 **THIS SHALL NOT BE USED.** Actually this is published nowhere so I have no idea why users end up having this conflicting package.

**Comment by mattip** [comment]
Hmm. Is there any way to distinguish between nvidia-ml-py and pynvml, and perhaps raise a helpful error or somehow integrate the two APIs? Looking at the download stats, [pynvml](https://pypistats.org/packages/pynvml) has about 113,500 / week, [nvidia-ml-py](https://pypistats.org/packages/nvidia-ml-py) has about 390,500 / week, so there are a lot of people using pynvml. I can understand them, anyone looking for the "natural" project to supply `pynvml` would assume the project name is `pynvml` not `nvidia-ml-py`.

**Comment by mattip** [comment]
[here](https://github.com/gpuopenanalytics/pynvml/network/dependents?dependent_type=PACKAGE) are the packages github detects as depending on `pynvml`. There are 156, some with over 1000 stars. I opened issues on the ones with lots of stars. :smile:

**Comment by wookayin** [comment]
I've added some error messages in the commit ab11ceb. It would be not difficult to make gpustat compatible with the non-official pynvml package, but let me figure out a good solution when I have more spare time.

**Comment by wookayin** [comment]
7c09a0f makes gpustat compatible even with @gpuopenanalytics/pynvml.

**Comment by sam-my-2023** [comment]
Had a similar issues today, also came with the['grpcio' issue](https://github.com/ray-project/ray/issues/33039) , either `pip install --force-reinstall --ignore-installed nvidia-ml-py ` or  'pip install --force-reinstall gpustat' did not solve the problem. Finally solved with 'conda install gpustat', both problems were solved. Don't know why, my os is ubuntu 22.04.

**Comment by wookayin** [comment]
You'll also need to do `pip uninstall pynvml` as well.

**Comment by BEpresent** [comment]
> `pip uninstall pynvml`

can confirm, this works

**Comment by zhiwenwang20122302** [comment]
pip uninstall pynvml

**Comment by cdj0311** [comment]
> You'll also need to do `pip uninstall pynvml` as well.

works well.

**Comment by wookayin** [comment]
(backported to v1.1.1 and released)
