### ISSUE TITLE
ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by Pagey** [wookayin/gpustat#155]
Hello!
I tried installing gpustat (latest? pip install) on an AWS EC2 Ubuntu (20.04) instance with Python3.10.10 and when running getting ModuleNotFoundError: No module named '_curses'

Is there a way around this? I used to use gpustat 0.6.0 in the past and it worked beautifully (wasn't installed with pip as far as I recall)
Thanks,
M

**Comment by wookayin** [comment]
Please use the bug report template and provide all the information necessary. If you installed latest gpustat 1.0.0, it should work. Gpustat no longer uses `_curses`, so I guess your installation is broken.

**Comment by wookayin** [comment]
See #156
