### ISSUE TITLE
That's cool 

### ISSUE THREAD

**Issue by bemoregt** [wookayin/gpustat#2]
That's cool 

But it is may be based on nvidia-smi ...

I need one that independent to nvidia-dmi.

Thanks at any rate.

**Comment by wookayin** [comment]
Do you mean we might need some executable that does not directly depend on nvidia-smi but use CUDA APIs to query gpu status? Or do you mean a non-NVIDIA monitoring tooling? Please clarify your message! Thanks.

**Comment by wookayin** [comment]
Please re-open the issue if you have any further points.
