### ISSUE TITLE
nvidia-ml-py version requirement

### ISSUE THREAD

**Issue by cjw85** [wookayin/gpustat#27]
I just upgraded to current HEAD from a previous version without nvidia-ml-py (I was planning to add in the power usage as in https://github.com/wookayin/gpustat/pull/13). I now get

    $ gpustat --debug
    Error on querying NVIDIA devices. Use --debug flag for details
    Traceback (most recent call last):
      File "/home/<user>/.local/lib/python2.7/site-packages/gpustat-0.4.0.dev1-
    py2.7.egg/gpustat.py", line 398, in print_gpustat
        gpu_stats = GPUStatCollection.new_query()
      File "/home/<user>/.local/lib/python2.7/site-packages/gpustat-0.4.0.dev1-
    py2.7.egg/gpustat.py", line 300, in new_query
        gpu_info = get_gpu_info(handle)
      File "/home/<user>/.local/lib/python2.7/site-packages/gpustat-0.4.0.dev1-
    py2.7.egg/gpustat.py", line 261, in get_gpu_info
        nv_graphics_processes = N.nvmlDeviceGetGraphicsRunningProcesses(handle)
    AttributeError: 'module' object has no attribute 'nvmlDeviceGetGraphicsRunningProcesses'

During installation I had:

    Searching for nvidia-ml-py==375.53.1
    Best match: nvidia-ml-py 375.53.1
    Adding nvidia-ml-py 375.53.1 to easy-install.pth file

So it looks like there are API differences between the versions of nvidia-ml-py. Can I ask which version you've been working with?

**Comment by wookayin** [comment]
It looks weird; 375.53.1 for me as well. I guess the following import also fails, right?

```
>>> import pynvml
>>> pynvml.nvmlDeviceGetGraphicsRunningProcesses
<function pynvml.nvmlDeviceGetGraphicsRunningProcesses>
>>> pynvml.__file__
'..(OMITTED)../site-packages/nvidia_ml_py-375.53.01-py2.7.egg/pynvml.pyc'
```

**Comment by cjw85** [comment]
Yes it does. I'll see if I can dig further. Thanks for now.

**Comment by cjw85** [comment]
OK, I installed in a virtual environment and had no issues. I then found that pynvml was being imported from /usr/local/lib/python2.7/dist-packages/ (Ubuntu 16.04) outside of the virtualenv, so I removed this. Things now work as expected.
