### ISSUE TITLE
Error trying to run gpustat: NVMLError_LibraryNotFound

### ISSUE THREAD

**Issue by trylks** [wookayin/gpustat#35]
Full message with `--debug` and Python3:

```
Error on querying NVIDIA devices. Use --debug flag for details
Traceback (most recent call last):
  File "/usr/local/bin/gpustat", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/gpustat.py", line 502, in main
    print_gpustat(**vars(args))
  File "/usr/local/lib/python3.6/dist-packages/gpustat.py", line 459, in print_gpustat
    traceback.print_exc(file=sys.stderr)
  File "/usr/lib/python3.6/traceback.py", line 159, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/usr/lib/python3.6/traceback.py", line 100, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "/usr/lib/python3.6/traceback.py", line 462, in __init__
    _seen.add(exc_value)
TypeError: unhashable type: 'NVMLError_LibraryNotFound'
```
I have also tried with Python2, just in case. Similar error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gpustat.py", line 454, in print_gpustat
    gpu_stats = GPUStatCollection.new_query()
  File "/usr/local/lib/python2.7/dist-packages/gpustat.py", line 254, in new_query
    N.nvmlInit()
  File "/usr/local/lib/python2.7/dist-packages/pynvml.py", line 747, in nvmlInit
    _LoadNvmlLibrary()
  File "/usr/local/lib/python2.7/dist-packages/pynvml.py", line 785, in _LoadNvmlLibrary
    _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/usr/local/lib/python2.7/dist-packages/pynvml.py", line 405, in _nvmlCheckReturn
    raise NVMLError(ret)
NVMLError_LibraryNotFound: NVML Shared Library Not Found
```

My guess is that I am missing some dependency, path, or correct version, but I could not find which is the problem yet. TBH I do not know how many layers of software are involved when running `gpustat`. I have the driver, its dev version, cuda, cuda toolkit,...

I hope/guess it is an easy to fix noob mistake. Do you have any idea  about the possible cause? Would  you like additional logs, version numbers, or anything?

PD: I had a bunch of nvidia things in version 387 and now I have moved to 384. I think in that process I have moved from Nvidia packages to Ubuntu packages too. After everything, it works, but that is all I know.

**Comment by Stonesjtu** [comment]
`gpustat` depends on the `pynvml`, which is a python wrapper for `nvml`. Does `nvidia-smi` work correctly? And can you add the output of `ldconfig -p | grep nvidia-ml`? I think the version mismatch between nvml and nvidia driver may cause this problem.

**Comment by wookayin** [comment]
Our package has nothing to do with the actual version of nvidia driver installed on the system. So, both 387 and 384 should work. But it seems that nvidia library installation is broken --- please provide us more detailed diagnosis as suggested by @Stonesjtu .

**Comment by trylks** [comment]
Sorry for the delay, I can only spend time on this computer every second weekend.

`nvidia-smi` works now, and it is the first time that I have seen it working. Here is the output of `ldconfig -p | grep nvidia-ml`:

```
	libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ml.so.1
	libnvidia-ml.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-ml.so.1
	libnvidia-ml.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ml.so
	libnvidia-ml.so (libc6) => /usr/lib32/nvidia-384/libnvidia-ml.so
```

It is very likely that versions did not match (and they match now). I may have mixed Ubuntu and Nvidia repositories/versions. I am not sure about what is the minimal and complete way to install the drivers, CUDA, and everything. I will investigate it further in the future.

I am trying to understand how all of this works and I am using `gpustat` to check that Xorg runs on the integrated Intel GPU (and not Nvidia GPU) and PyTorch runs in the Nvidia GPU (and not in the Intel CPU). So thank you for this tool, it is extremely useful.

**Comment by Stonesjtu** [comment]
well, I personally recommand you to uninstall all the nvidia driver packages provided by ubuntu, and install via nvidia binary. One reason is that the apt version is not the newest version, another is that  they are error-probe to versiob mismatch problem after certain upgrade operations.

**Comment by trylks** [comment]
I understand and I agree, but it is hard to know which packages are involved and their dependencies, this is why installed Ubuntu and not Debian. I do not know how many things could break, e.g. I know about Optimus and Bumblebee, but I do not know how many things I may not know.

Do you know if there is any comprehensive guide so that I can have CUDA with all the bells and whistles running and keep the peace of mind of knowing that my laptop will not burn out, the integrated Intel GPU will be used, etc.?

There are many packages involved, the documentation of each of them is extensive, but I found no general overview of which packages should be installed and how they play with each other.

If you don't know about such a reference, or you think it does not exist, that is fine [I will try to make it](https://github.com/trylks/trylks/blob/master/linux/install.md), I will not make it soon, though.

Thank you very much.

**Comment by wookayin** [comment]
Closing this, considered as not a problem related `gpustat` itself. However, we could come up with a better exception message for python 3 ([due to traceback module](https://bugs.python.org/issue28603)).

**Comment by skjerns** [comment]
sure:

```
Ran 6 tests in 2.335s

OK
```
