### ISSUE TITLE
Installed GPU but got error ImportError: No Module named gpustat

### ISSUE THREAD

**Issue by Humayun-CF** [wookayin/gpustat#38]
I installed gpustat using below command, when I run gpustat, I got error: ImportError: No module named gpustat. Do I need to set the path variable to a specific location. 

"ubuntu@lambda-quad:~$ sudo -H pip install git+https://github.com/wookayin/gpustat.git@master 
Collecting git+https://github.com/wookayin/gpustat.git@master
  Cloning https://github.com/wookayin/gpustat.git (to master) to /tmp/pip-hIbHPs-build
  Requirement already satisfied (use --upgrade to upgrade): gpustat==0.5.0.dev1 from git+https://github.com/wookayin/gpustat.git@master in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six>=1.7 in /usr/local/lib/python2.7/dist-packages (from gpustat==0.5.0.dev1)
Requirement already satisfied: nvidia-ml-py>=7.352.0 in /usr/local/lib/python2.7/dist-packages (from gpustat==0.5.0.dev1)
Requirement already satisfied: psutil in /usr/local/lib/python2.7/dist-packages (from gpustat==0.5.0.dev1)
Requirement already satisfied: blessings>=1.6 in /usr/local/lib/python2.7/dist-packages (from gpustat==0.5.0.dev1)"

"ubuntu@lambda-quad:~$ gpustat
Traceback (most recent call last):
  File "/usr/local/bin/gpustat", line 9, in <module>
    load_entry_point('gpustat==0.5.0.dev1', 'console_scripts', 'gpustat')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named gpustat
"

**Comment by Stonesjtu** [comment]
Can you run `python2.7 -c 'import gpustat; print(gpustat.__file__)'?

**Comment by Humayun-CF** [comment]
Thanks for response. 
Here is output: 

"ubuntu@lambda-quad:~$ python2.7 -c 'import gpustat; print(gpustat.file)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named gpustat"

"ubuntu@lambda-quad:~$ python --version
Python 2.7.12"

**Comment by Stonesjtu** [comment]
im afraid that /usr/local/lib/python2.7 is not in your python's default search path

**Comment by Humayun-CF** [comment]
what should I do? this code only run in python 2.7.

**Comment by Stonesjtu** [comment]
Sorry for the late reply, this bug is probably introduced by #33 which doesn't include the core file in package.
For a workaround, you may checkout older version and runs `pip install .`, or install from *pypi* via `pip install gpustat`.
