### ISSUE TITLE
*features*  First thank you for your coding and I am very happy to find a way to get GPU stat better ?

### ISSUE THREAD

**Issue by zxqchat** [wookayin/gpustat#40]
I want to monitor a GPU status and I can use another program continue when a program stoped .Do you have any good idea ? 
thank you for your  coding,if you have any trouble in reading my issures ,you can contact me .my native language is not english .

**Comment by Stonesjtu** [comment]
What do you mean by "one program continues when the other stops".

2018-05-15 20:56 GMT-07:00, Cour <notifications@github.com>:

**Comment by zxqchat** [comment]
@Stonesjtu yes , I want to implement this function, but I have a little worry about the monitor process will waste the system resource. Because it will continues to monitor at all time.

**Comment by Stonesjtu** [comment]
Well, you may just query the gpu information at your favored frequency. For me, it costs little CPU time (<5% probably) to query once per sec.

**Comment by zxqchat** [comment]
@Stonesjtu I found a good way to implement my idea. through judge the PID status . it also can be useful.
