### ISSUE TITLE
Problem with pynvml dependency and python 3.6

### ISSUE THREAD

**Issue by johann-petrak** [wookayin/gpustat#46]
When I try to run this using Python 3.6.4 (Anaconda) I get:

```
    import pynvml as N
  File "${PYTHONPATH}/lib/python3.6/site-packages/pynvml.py", line 1831
    print c_count.value
```
This can be fixed by using the module py3nvml instead and replacing line 24 in gpustat/core.py with
```
from py3nvml import py3nvml as N
```

**Comment by johann-petrak** [comment]
I re-installed gpustat, tried first without the -U flag and it worked even then already, depending on nvidia-ml-py3, as you say. 
No idea at all why I had this problem initially at all!

**Comment by Stonesjtu** [comment]
It’s a bug fixed after you have installed the old version of `gpustat`.
Either `pip install -U gpustat` or reinstall will get you the newest gpustat.
