### ISSUE TITLE
gpustat -cp does not refresh the stats

### ISSUE THREAD

**Issue by lapwat** [wookayin/gpustat#52]
gpustat -cp should refresh every x seconds like in the screenshot of the readme. The current behavious is that gpustat -cp runs one iteration then closes.

gpustat -cp, gpustat -c, gpustat -p and gpustat return the same output:

```sh
[0] GeForce MX150    | 39'C,   0 % |     0 /  2002 MB |
```

Python 3.7.0

Thank you

**Comment by Stonesjtu** [comment]
If you want to display the information continuously, you should run with extra option `-i 1`.
For the lack of process information, could you plz post the driver version and system environment.

**Comment by lapwat** [comment]
Ok my bad. I did not RTFM. The screenshot was not updated. It works well with `-i` option.
I am running Archlinux with Nvidia's official drivers.

Thank you for your time.
