### ISSUE TITLE
use too much CPU resource

### ISSUE THREAD

**Issue by matthew-z** [wookayin/gpustat#54]
Hi, `gpustat -i` uses about 80% CPU on my machine, is it expected or a bug?
 In contrast, `nvidia-smi -l 1` uses less than 10%.

OS: Ubuntu 18.04
Nv Driver: 410.48
CUDA: 10.0.130
CPU: AMD Threadripper 1900x
GPU: 2080Ti + 1080

<img width="820" alt="image" src="https://user-images.githubusercontent.com/5741303/48206004-b67a0780-e3b0-11e8-89d6-6a8f10f184b7.png">

**Comment by Stonesjtu** [comment]
whats your interval value

**Comment by matthew-z** [comment]
I didn't set, but `gpustat -i 1` will reproduce the same result.

**Comment by matthew-z** [comment]
I tested, and with `watch -n 1` they use the same amount of CPU time (about 0-20%).

**Comment by matthew-z** [comment]
Hi, I just found that the CPU time problem of `gpustat -i`  can be solved  by running `nvidia-smi daemon` first.

**Comment by wookayin** [comment]
A difference is that in the watch mode (i.e. `gpustat -i`) we fetch handle resources *at every time step*, which is somewhat expensive. Therefore we could optimize in a way that GPU handles are fetched only once in the beginning, and use the (cached) resources. This would be possible in the watch mode as the gpustat process won't terminate until interrupted.

**Comment by wookayin** [comment]
Working on #61.
In my case querying power usage is most expensive, so I made it optional whenever possible. Could anybody check whether it leads to less CPU usage?

**Comment by JalinWang** [comment]
> A difference is that in the watch mode (i.e. `gpustat -i`) [handle resources are fetched](https://github.com/wookayin/gpustat/blob/v0.5.0/gpustat/core.py#L372) _at every time step_, which is somewhat expensive. Therefore we could optimize in a way that GPU handles are fetched only once in the beginning, and use the (cached) resources. This would be possible in the watch mode as the gpustat process won't terminate until interrupted.

But I still have no idea of the difference between "watch -n 1 gpustat" and "gpu -i 1".
Both of them need to call print_gpustat() every tick, while 'watch' requires additional step to parse command line arguments again and again. So intuitively the former should took longer.


BTW, here is the source code of 'watch' if needed: [watch.c](https://gitlab.com/procps-ng/procps/-/blob/master/watch.c), where I found nothing useful : (

**Comment by Stonesjtu** [comment]
Ter,

The most time is not spent on parsing CLI options actually, which only requires several us at most.

**Comment by rkooo567** [comment]
Has this issue been resolved? I am observing this behavior from https://github.com/ray-project/ray/ when we run gpustat.new_query() repetitively at GCE. 

![profile](https://github.com/wookayin/gpustat/assets/18510752/5db64f3b-b3a7-4e4a-ac6b-93e603159ac4)

**Comment by rkooo567** [comment]
Lots of time is spent on NvmlInit & shutdown & nvmlDeviceGetHandleByIndex

**Comment by wookayin** [comment]
In the recent versions of pynvml, `nvmlDeviceGetHandleByIndex` doesn't seem to be a bottleneck according to profiling result (If this is still slow, please let me know) so I did not optimize on redundant calls of `nvmlDeviceGetHandleByIndex`. #166 makes `nvmlInit()` called only once, so it should have some performance benefit.
