### ISSUE TITLE
Drop Python 2 Support

### ISSUE THREAD

**Issue by bethune-bryant** [wookayin/gpustat#66]
@Stonesjtu [Pointed out that Python 2 is being retired](https://github.com/wookayin/gpustat/pull/65#issuecomment-512323532):

> python2.7 is retiring in Jan 1st 2020, so probably the master branch can focus on only python 3.
Ref. https://pythonclock.org/

> According to https://stackoverflow.com/questions/40114100/uploading-different-versions-python-2-7-vs-3-5-to-pypi, we can simply add python_requires='>=3.4' and bump the version.
Then if you install the package via pip2, the out-dated one instead of the newest version will be selected.

**Comment by wookayin** [comment]
Speaking of retiring python2, I think this would be the best time to version our gpustat finally as 1.0.

**Comment by bethune-bryant** [comment]
> 
> 
> Speaking of retiring python2, I think this would be the best time to version our gpustat finally as 1.0.

@wookayin 

Let me know if there's anything you want me to do for this.

**Comment by ofek** [comment]
@wookayin Then you could also resolve #57 by using https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size

**Comment by bethune-bryant** [comment]
Resolved by #67
