### ISSUE TITLE
We need a better way to display cmd name of running process on one card.

### ISSUE THREAD

**Issue by lartpang** [wookayin/gpustat#68]
![image](https://user-images.githubusercontent.com/26847524/62422443-5e74f500-b6e5-11e9-9b27-4619da8e4009.png)

These contents are too messy. Can this tool be able to display line breaks between different cmds?

**Comment by wookayin** [comment]
I agree. In case where the command line contains full arguments we should trim args away.

BTW I didn't get your point of 'display line breaks'. Would you please elaborate on this?

**Comment by wookayin** [comment]
If you meant displaying one process (one command line) at a line, this is already implemented: please try out #50 and #65.

**Comment by lartpang** [comment]
That basically is similar to what I want to say. Thanks.

**Comment by lartpang** [comment]
I used the version `0.6.0` from `pypi` before, and then directly updated to the `1.0.0` version of the repository on GitHub, it is fine now.
