### ISSUE TITLE
D(isk sleep) status when using gpustat -i

### ISSUE THREAD

**Issue by wildkid1024** [wookayin/gpustat#70]
when I use ```gpustat -i``` to watch my GPU usage in  SSH, but my local computer is shutdowm unexpectedly. When I open my server in SSH, I find that  the process becomes a D(isk sleep) status and i can’t kill it. I have no permission to reboot, how can I slove it?

**Comment by Stonesjtu** [comment]
Have you tried `kill -9`

**Comment by wildkid1024** [comment]
> Have you tried `kill -9`

I tried, but it is useless.

**Comment by Stonesjtu** [comment]
Can you share your `interval` value, when running `gpustat -i`.

**Comment by wookayin** [comment]
Closing as obsolete; I don't think the bug has something to do with gpustat. Please feel free to reopen if it's still an issue for you.
