### ISSUE TITLE
python 2.7  Command 'gpustat' not found

### ISSUE THREAD

**Issue by XinyuLyu** [wookayin/gpustat#71]
![image](https://user-images.githubusercontent.com/33551398/65562803-3fbf0c00-df7a-11e9-88b8-42e422f0432e.png)
![image](https://user-images.githubusercontent.com/33551398/65562829-54030900-df7a-11e9-9ce6-8ac5a1d58078.png)

**Comment by Stonesjtu** [comment]
You should add `$HOME/.local/bin` to your PATH.

**Comment by chovy** [comment]
this should be in docs. if you don't use `sudo pip`

**Comment by Stonesjtu** [comment]
Well, if you use anaconda / miniconda, then everything is set up already. And it's rather a `pypi` issue, leaving it in issue should be fine in my opinion.
