### ISSUE TITLE
Not supported

### ISSUE THREAD

**Issue by talentlessguy** [wookayin/gpustat#72]
# What I tried

```
➜ gpustat
v1rtl-CR70-2M-CX70-2OC-CX70-2OD  Fri Oct  4 21:22:05 2019  390.116
[0] GeForce GT 740M  | 64'C,  ?? % |   360 /  2004 MB | (Not Supported)
```

# Problem

gpustat doesn't show anything

# Reason

`nvidia-smi` also shows "Not supported"

# Details

**OS** Ubuntu 18.04
**GPU** NVIDIA GT 740M

**Comment by Stonesjtu** [comment]
The hardware cannot show the processes running on it.

**Comment by talentlessguy** [comment]
> The hardware cannot show the processes running on it.

`gmonitor` works though:

![image](https://user-images.githubusercontent.com/35937217/66256114-5f80dc00-e793-11e9-92d2-c7a01791f03b.png)

**Comment by Stonesjtu** [comment]
I don't see the processes in the screenshot though.

**Comment by talentlessguy** [comment]
@Stonesjtu, then closing bc can't be fixed (my nvidia is 740m which seems to be too old)

**Comment by hstk30** [comment]
Hi, I meet this problem also. But, my `nvidia-smi` can show process info, but `gpustat` is show `Not Supported` about process info. I upgrade `gpustat` 0.4.1 to 0.6 still not work. 
Is `gpustat` need some Authority to access process info ?

**Comment by wookayin** [comment]
This is probably when your **driver version is too old**. gpustat does not require any sudo privileges 

Other scenarios includes when a multi-instance GPU (MIG) is used: see #102. Or, as of 2022, it could also happen when nvidia drivers and pynvml version are not compatible. Please read README for more information, and open a new issue if you still have the same problem.
