### ISSUE TITLE
Feature request: Cluster GPU monitoring

### ISSUE THREAD

**Issue by Michaelvll** [wookayin/gpustat#73]
Hi,

Thank you for your great tool for monitoring GPU usage, showing much clearer information than `nvidia-smi`. 

## Feature
Currently, I am working on a cluster with multiple GPU nodes. Do you think it would be a good idea to support monitoring for multiple nodes on one node? The use case is described as follows.

## Use case
For a user with two nodes n1 and n2, it would be great if we can run the following command to show the GPU usage on all nodes.
```bash
gpustat -a -i 1 -s n1,n2
```
Displaying:
n1 *time* *cuda version*
*GPU information*

n2 *time* *cuda version*
*GPU information*

## Possible Implementation
One of the possible implementations would be to start a `gpustat` service on each given node by sending commands with `ssh` and then on the master node, collect the information from each server periodically.

**Comment by wookayin** [comment]
Try https://github.com/wookayin/gpustat-web

**Comment by Michaelvll** [comment]
Thank you for your reply. That project looks great!

**Comment by JiankunW** [comment]
Here is a simple script, based on `gpustat`, for monitoring GPU usages on a Slurm cluster.
https://gist.github.com/JiankunW/ade629366f0c43beb6d3cb1f5fbfd0c1

Easy to modify this script and adopt to other cluster systems.
