### ISSUE TITLE
nvidia-smi is not recognized as an internal or external command: with 0.3.x versions on windows

### ISSUE THREAD

**Issue by gotonickpappas** [wookayin/gpustat#74]
C:\>gpustat -cp
'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.
Error on calling nvidia-smi

C:\>nvidia-smi --query-gpu=index,uuid,name,temperature.gpu,utilization.gpu,memory.used,memory.total --format=csv,noheader,nounits
0, GPU-9d01c9ef-1d73-7774-8b4f-5bee4b3bf644, GeForce GTX 1080 Ti, 28, 65, 9219, 11264
1, GPU-9da3de3f-cdf2-8ca9-504d-fd9bc414a78e, GeForce GTX 1080 Ti, 22, 0, 140, 11264

Any idea what might be the issue? 
Windows 10, Python 3.7.2, latest nvidia drivers, etc, as of the time of this post.

**Comment by Stonesjtu** [comment]
Can you check the version of gpustat

**Comment by gotonickpappas** [comment]
0.3.2

**Comment by Stonesjtu** [comment]
Can you please upgrade the gpustat.

**Comment by gotonickpappas** [comment]
Hmm, I just noticed that the upgrade through pip grabbed a 0.* version.

C:\>pip install --upgrade gpustat
Collecting gpustat
  Using cached https://files.pythonhosted.org/packages/b4/69/d8c849715171aeabd61af7da080fdc60948b5a396d2422f1f4672e43d008/gpustat-0.6.0.tar.gz
Requirement already satisfied, skipping upgrade: six>=1.7 in 
.
.
.
Installing collected packages: gpustat
  Found existing installation: gpustat 0.3.2
    Uninstalling gpustat-0.3.2:
      Successfully uninstalled gpustat-0.3.2
    Running setup.py install for gpustat ... done
Successfully installed gpustat-0.6.0

C:\>gpustat -cp
Traceback (most recent call last):
 .
.
.
.
ModuleNotFoundError: No module named '_curses'

C:\>

**Comment by Stonesjtu** [comment]
Related to #69. We are trying to support windows at next release.

**Comment by wookayin** [comment]
Closing as invalid (outdated version and nvidia-smi is not installed) or duplicated.

**Comment by gotonickpappas** [comment]
Actually it is not invalid. 
nvidia-smi IS installed.

Using latest version givers error about no module named '_curses'
(thus I installed a previous version that had no such error, but would give a different one.)
Hence the opening an issue.

The problem remains.

**Comment by wookayin** [comment]
This is the problem that only happens with 0.3.x versions (that rely on nvidia-smi command) on Windows. Pythons in windows does not respect $PATH so the absolute path must be specified manually. Although 0.3.x series not supported anymore but since the latest versions also don't work on windows, I will have this issue open.

**Comment by kakimochi** [comment]
> ModuleNotFoundError: No module named '_curses'

I have fixed this issue on my situation. Please try the followings.
pip install windows-curses

**Comment by gotonickpappas** [comment]
@kakimochi Yeah that will install _curses alright, but leads to this:
https://github.com/wookayin/gpustat/issues/57

**Comment by wookayin** [comment]
Support for windows will be tracked in #57. Closing this as duplicate.

**Comment by khanakbar145** [comment]
To solve this problem [click here ](https://youtu.be/yCMFygZ5SBA)
