### ISSUE TITLE
Maximum Sampling Rate of GPU Power

### ISSUE THREAD

**Issue by europa1610** [wookayin/gpustat#76]
Hey! This might be slightly unrelated but I was wondering what the maximum sampling rate of call to `nvmlDeviceGetPowerUsage` would be. It must be limited by the sampling rate of the power measurement hardware on the GPU. Do you know about this based on your usage of the NVML API?

Thanks!

**Comment by Stonesjtu** [comment]
We are now restricting the sampling rate to be lower than 10/sec (interval >= 0.1s), however you may try even higher rate to see what happens. 

https://github.com/wookayin/gpustat/blob/fb0f54e93ddbda24c72b32cef860a766203858cc/gpustat/cli.py#L127

**Comment by europa1610** [comment]
Thanks! I tried a very high sampling rate (calling `nvmlDeviceGetPowerUsage` without any delay) and the number of samples achieved in 1 second is around 2743, however, I don't think GPU power measurement hardware can have 2.7kHz sampling rate (I am using a Tesla K40m). I think the function returns the last measured power if we try to call it when the power measurement hardware is not ready or has recently returned a measured power from the sensor. 
I will try the NVIDIA developer forums for exact sampling rate figures.
Closing this issue.

**Comment by piotr-dobrogost** [comment]
@europa1610 
Could you please share a link to the forum post you refer to?

**Comment by europa1610** [comment]
Hey @piotr-dobrogost I posted my query on the NVIDIA Devtalk forums (NVML Subtopic) [here](https://devtalk.nvidia.com/default/board/76/system-management-and-monitoring-nvml-/) but haven't received a response to my query yet. Here's [my post](https://devtalk.nvidia.com/default/topic/1069213/system-management-and-monitoring-nvml-/maximum-sampling-rate-of-gpu-power-measurement-using-nvml/) for reference.
