### ISSUE TITLE
Expose GPU enc/dec utilization

### ISSUE THREAD

**Issue by ChaoticMind** [wookayin/gpustat#79]
Looks like the `utilization.gpu` value right now is the one shown via `nvidia-smi` (as `GPU-Util`).

If one runs `nvidia-smi dmon` instead, it also exposes a percentage representing encoding/decoding utilization (as a percentage under the `enc`and `dec` columns).

Any chance of including those in `gpustat`? I'm running into a case where `enc` is at or near 100%, but the general GPU utilization is at a much lower ~25%, so it can't effectively be used as a proxy.

**Edit**: I see gpustat is using `nvmlDeviceGetUtilizationRates`, but the API also exposes `nvmlDeviceGetEncoderUtilization`and `nvmlDeviceGetDecoderUtilization` which would probably be what we're looking for.

**Comment by Stonesjtu** [comment]
The statistics are easy to obtain.
but any ideas on how to present these numbers on console output?

**Comment by ChaoticMind** [comment]
@Stonesjtu One way would be to just include expose it after GPU utilization:

Instead of:
GeForce GTX TITAN 0 | 80°C,  76 % |  8000 / 12287 MB | user1(4000M) user2(4000M)

We could have:
GeForce GTX TITAN 0 | 80°C,  76 % (**enc**: 66 %, **dec**: 53 %|  8000 / 12287 MB | user1(4000M) user2(4000M)

Although it might make sense to hide it behind a cmdline flag.

I made a PR without exposing the numbers to the console output, because my use case doesn't currently require it. Let me know if you prefer to include the info in the commandline, and I could add another commit to the #79.

**Comment by Stonesjtu** [comment]
Addressed in #80
