### ISSUE TITLE
Support Python2.6

### ISSUE THREAD

**Issue by wookayin** [wookayin/gpustat#8]
Python2.6 doesn't support dict comprehension syntax.

```
  File "gpustat.py", line 168
    g = GPUStat({col_name: col_value.strip() for \
                                               ^
SyntaxError: invalid syntax
```

**Comment by hamidmosaddeghi** [comment]
hi 

I check gpustat by python 2.6 and 2.7 , then I get same error.

**Comment by wookayin** [comment]
And no `check_output` and `CalledProcessError` :(

**Comment by wookayin** [comment]
We won't support python 2.6 because it is too legacy.
