### ISSUE TITLE
The display of power usage is confused

### ISSUE THREAD

**Issue by ShougangShen** [wookayin/gpustat#83]
As shown in the figure,
![图片](https://user-images.githubusercontent.com/47826632/80223677-323a4380-867b-11ea-9335-c407280116de.png)

I run the `gpustat -i -a`

**Comment by wookayin** [comment]
Why do you think it is confusing? The reason you see `??` is because your graphic card does not support power limit and/or fan speed. Could you try seeing what `nvidia-smi` reads?

**Comment by ShougangShen** [comment]
I see, Thanks
