### ISSUE TITLE
Weird output on Windows 10

### ISSUE THREAD

**Issue by eusoubrasileiro** [wookayin/gpustat#86]
Just downloaded the master version to run on Windows after https://github.com/wookayin/gpustat/issues/57#issuecomment-619813700

Got the following error installing from conda:

`pip install git+https://github.com/wookayin/gpustat`

```
gpustat --debug
Error on querying NVIDIA devices. Use --debug flag for details
Traceback (most recent call last):
  File "d:\anaconda3\lib\site-packages\pynvml.py", line 641, in _LoadNvmlLibrary
    nvmlLib = CDLL(os.path.join(os.getenv("ProgramFiles", "C:/Program Files"), "NVIDIA Corporation/NVSMI/nvml.dll"))
  File "d:\anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda3\lib\site-packages\gpustat\cli.py", line 20, in print_gpustat
    gpu_stats = GPUStatCollection.new_query()
  File "d:\anaconda3\lib\site-packages\gpustat\core.py", line 362, in new_query
    N.nvmlInit()
  File "d:\anaconda3\lib\site-packages\pynvml.py", line 608, in nvmlInit
    _LoadNvmlLibrary()
  File "d:\anaconda3\lib\site-packages\pynvml.py", line 646, in _LoadNvmlLibrary
    _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "d:\anaconda3\lib\site-packages\pynvml.py", line 310, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
```

I solved the first error by copying the `nvml.dll` from `Windows\System32` to the above folder. 
Then I had to run anaconda prompt as administrator 

Then it runs, for example `gpustat -a --watch 1` produces 

![image](https://user-images.githubusercontent.com/4503573/81339681-f04ecb80-9084-11ea-81a1-7e5c9a2446d6.png)

I think something is wrong... is it? is showing a lot of process.
Python 3.7.6

#### pip  package from nvidia `nvidia-smi-py` translated to python 3

https://forums.fast.ai/t/show-gpu-utilization-metrics-inside-training-loop-without-subprocess-call/26594

#### limitations of nvidia-smi on Windows 

https://stackoverflow.com/q/44227767/1207193

- dont show memory usage and processes with `Insufficient Permissions`

**Comment by wookayin** [comment]
Hi @eusoubrasileiro, thanks for the report. I suspect that processes that are using GPU for graphics rendering is appearing (See #18 for details). Maybe we should disable this by default or at least make it configurable. /cc @kapsh 

Could you try the following to make sure this is the case?

```python3
import pynvml as N
N.nvmlInit()
handle = N.nvmlDeviceGetHandleByIndex(0)
procs = N.nvmlDeviceGetGraphicsRunningProcesses(handle)
for p in procs:
    print(p.pid, p)
```

If it shows the same list of processes as above, my guess would be correct.

**Comment by eusoubrasileiro** [comment]
Yes, exactly that's it they are all using geforce gtx1060, also showing on activity on system tray. 
Well I guess this is not a bug than. Yes I really would like to see only those using a CUDA, is it possible?

**Comment by wookayin** [comment]
Could you also show me the full output of `nvidia-smi` (especially the `Processes:` part)? I am leaning to excluding graphics process by default. I will add an option to make it configurable.

**Comment by kapsh** [comment]
@wookayin hello. As I understand, the reason of this issue (as it was in #18 mentioned above) is that some users expect to see CUDA applications listed while others expect graphics users being listed. Correct? 
If that so, the right way would be introducing separate options to choose the mode explicitly (and possibly combine them).

**Comment by wookayin** [comment]
Closing this issue as the error (nvml not found) was resolved. A similar issue is being tracked in #90 (which we will improve on).

For excluding graphics applications from the process list, please see #26.
