### ISSUE TITLE
Questions about gpustat display memory usage logic

### ISSUE THREAD

**Issue by ganler** [wookayin/gpustat#89]
Hi, I was writing some GPU memory usage monitoring codes using `nvmlDeviceGetComputeRunningProcesses`. And I used gpustat for debugging. I found that gpustat reported about 5x memory usage than my program. 

Did I use nvmlDeviceGetComputeRunningProcesses in the wrong way? How is the display logic of the yellow number below? (I tried to look at the source codes but did not find out the logic)

gpustat 
![image](https://user-images.githubusercontent.com/38074777/86749664-00c4f780-c070-11ea-97c1-01c4ee115df9.png)

My codes
![image](https://user-images.githubusercontent.com/38074777/86749722-0ae6f600-c070-11ea-9df8-80328c346939.png)

**Comment by Stonesjtu** [comment]
Can you post the output of nvidia-smi

**Comment by ganler** [comment]
@Stonesjtu It is the same as `gpustat`. 

The logic of my program goes like this: 
- Use `nvmlDeviceGetComputeRunningProcesses` to query process information.
- Get the process information item whose pid is equal to current pid.
- Use the `usedGpuMemory` data member.

**Comment by ganler** [comment]
![image](https://user-images.githubusercontent.com/38074777/86773337-21994700-c088-11ea-8aba-6a3cc9d30935.png)

**Comment by wookayin** [comment]
So what is wrong here? You said gpustat and nvidia-smi report the same memory usage.

**Comment by wookayin** [comment]
FYI, we basically use the same API (`nvmlDeviceGetComputeRunningProcesses` and `usedGpuMemory`).

**Comment by ganler** [comment]
> FYI, we basically use the same API (`nvmlDeviceGetComputeRunningProcesses` and `usedGpuMemory`).
> 
> https://github.com/wookayin/gpustat/blob/v0.6.0/gpustat/core.py#L305
> https://github.com/wookayin/gpustat/blob/v0.6.0/gpustat/core.py#L346

Hi @wookayin , I think this is my problem. I meant to monitor my C++ program's GPU memory usage via `nvmlDeviceGetComputeRunningProcesses` but could not get the result as gpustat and nvidia-smi. It seems to be my problem and I should try to debug my program. 

Thank you for your patience. Closed.

**Comment by wookayin** [comment]
No worries. I think your program and gpustat are using the same API so you should be able to get the exactly same result. Please let us know if there's anything we could help with.
