### ISSUE TITLE
What do the columns indicate?

### ISSUE THREAD

**Issue by joshlk** [wookayin/gpustat#97]
Sorry to ask a dumb question, but what do the columns in GPU stat indicate? I couldn't find an explanation in the readme.

**Comment by wookayin** [comment]
I think this is very obvious, but let me explain for you:

[0] GeForce GTX Titan X | 77'C,  96 % | 11848 / 12287 MB | python/52046(11821M)

* [0]: GPUindex (starts from 0) as PCI_BUS_ID
* GeForce GTX Titan X: GPU name
* 77'C: Temperature
* 96 %: Utilization
* 11848 / 12287 MB: GPU Memory Usage
* python/...: Running processes on GPU (and their memory usage)

Compare the output from nvidia-smi.

**Comment by joshlk** [comment]
Thanks 😃 . I have done a PR to add the information to the readme #98
